### PR TITLE
updating the summary field to account for string and international

### PR DESCRIPTION
**Pull request by acornett21**
Motivation:
- A Partner was failing preflight checks container due to the use of the below library
```
{0, "mongocli", "1.20.3", "1", "x86_64", "mongocli-1.20.3-1.src.rpm", 12996608, "Apache 2.0", "MongoDB Inc.", "", "MongoDB Command Line Interface (mongocli) is a tool for managing your MongoDB cloud services, like MongoDB Atlas, MongoDB Cloud Manager, and MongoDB Ops Manager.", "RSA/SHA1, Thu Sep 30 14:39:13 2021, Key ID b00a0bd1e2c63c11", nil, nil, nil},
```

- After Debugging I found that the header tag value was a `6` (string) instead of the `9` (international string) that we expect. I'm not sure why this is the case. 
- Updated to include string as a type we include in the summary along with international string
- Relates: redhat-openshift-ecosystem/openshift-preflight#694

Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Review by komish — APPROVED** [review]
It feels super strange to me, mostly because as far back as I can see, the support for international strings when creating rpms has been in place... and all the docs seem to indicate that this is the right type for that metadata element...

All that said, if this resolves the issue, even if just temporarily, I'll LGMT it. Probably best to have @bcrochet review on return.

/lgtm

**Comment by komish** [comment]
https://github.com/rpm-software-management/rpm/blob/7d38c6e2d80492ba32814e4ad1175247fab3d931/lib/tagexts.c#L383
https://rpm-software-management.github.io/rpm/manual/tags.html
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-package-structure.html

**Comment by bcrochet** [comment]
I would expect to see a test case added that would trigger this.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Pull request merged**
